reload:
enquire_deliveries_by_scenario:
enquire_last_notification:
enquire_scenarios:
enquire_active_scenarios:
  fields:
    trace:
      required: false
      selector:
        boolean:
enquire_occupancy:
enquire_snoozes:
refresh_entities:
clear_snoozes:
purge_archive:
  fields:
    days:
      required: false
      example: 5
      selector:
        number:
          min: 0
          unit_of_measurement: days

snooze:
  fields:
    minutes:
      required: false
      example: 60
      selector:
        number:
          min: 0
          unit_of_measurement: minutes
    target_type:
      required: false
      selector:
        text:
    target:
      required: false
      selector:
        text:
