reload:
notify:
  fields:
    message:
      required: true
      selector:
        text:
          multiline: true
    title:
      selector:
        text:
    target:
      selector:
        target:
    priority:
      selector:
        select:
          options:
            - critical
            - high
            - medium
            - low
            - minimum
    delivery_selection:
      selector:
        select:
          options:
            - explicit
            - fixed
            - implicit
    delivery:
      selector:
        object:
    require_scenarios:
      selector:
        text:
          multiple: true
    apply_scenarios:
      selector:
        text:
          multiple: true
    constrain_scenarios:
      selector:
        text:
          multiple: true
    action_groups:
      selector:
        text:
          multiple: true
    actions:
      selector:
        object:
    media:
      selector:
        object:
    message_html:
      selector:
        text:
          multiline: true
    debug:
      selector:
        boolean:
    force_resend:
      selector:
        boolean:
    data:
      selector:
        object:
enquire_configuration:
enquire_deliveries_by_scenario:
enquire_implicit_deliveries:
enquire_last_notification:
  fields:
    diagnostics:
      required: false
      selector:
        boolean:
enquire_recipients:
enquire_scenarios:
enquire_active_scenarios:
  fields:
    trace:
      required: false
      selector:
        boolean:
enquire_occupancy:
enquire_snoozes:
refresh_entities:
clear_snoozes:
purge_media:
  fields:
    days:
      required: false
      example: 5
      selector:
        number:
          min: 0
          unit_of_measurement: days
purge_archive:
  fields:
    days:
      required: false
      example: 5
      selector:
        number:
          min: 0
          unit_of_measurement: days
