from __future__ import annotations

from typing import TYPE_CHECKING, Any

from homeassistant.const import CONF_ACTION, CONF_ENABLED, CONF_TARGET

from custom_components.supernotify.const import (
    CONF_DELIVERY_DEFAULTS,
    CONF_SELECTION,
    CONF_TRANSPORT,
    SELECTION_BY_SCENARIO,
    TRANSPORT_ALEXA,
    TRANSPORT_ALEXA_MEDIA_PLAYER,
    TRANSPORT_CHIME,
    TRANSPORT_EMAIL,
    TRANSPORT_GENERIC,
    TRANSPORT_NOTIFY_ENTITY,
    TRANSPORT_PERSISTENT,
    TRANSPORT_SMS,
)
from custom_components.supernotify.transports.generic import GenericTransport
from custom_components.supernotify.transports.notify_entity import NotifyEntityTransport
from custom_components.supernotify.transports.persistent import PersistentTransport
from custom_components.supernotify.transports.telegram import TelegramTransport

from .hass_setup_lib import TestingContext

if TYPE_CHECKING:
    from homeassistant.core import HomeAssistant

    from custom_components.supernotify.context import Context

DELIVERY: dict[str, Any] = {
    "email": {CONF_TRANSPORT: TRANSPORT_EMAIL, CONF_ACTION: "notify.smtp"},
    "text": {CONF_TRANSPORT: TRANSPORT_SMS, CONF_ACTION: "notify.sms"},
    "chime": {CONF_TRANSPORT: TRANSPORT_CHIME, "target": ["switch.bell_1", "script.siren_2"]},
    "alexa_devices": {CONF_TRANSPORT: TRANSPORT_ALEXA, CONF_ACTION: "notify.send_message"},
    "alexa_media_player": {CONF_TRANSPORT: TRANSPORT_ALEXA_MEDIA_PLAYER, CONF_ACTION: "notify.alexa_media_player"},
    "chat": {CONF_TRANSPORT: TRANSPORT_GENERIC, CONF_ACTION: "notify.my_chat_server"},
    "persistent": {CONF_TRANSPORT: TRANSPORT_PERSISTENT, CONF_SELECTION: [SELECTION_BY_SCENARIO]},
}


async def test_simple_create_with_defined_default_delivery() -> None:
    delivery_config = DELIVERY.copy()
    delivery_config["chat"]["selection"] = "default"
    ctx = TestingContext(deliveries=delivery_config, transport_types=[GenericTransport])
    await ctx.test_initialize()

    assert list(ctx.delivery_registry.deliveries.keys()) == ["chat"]
    assert [d.name for d in ctx.delivery_registry.implicit_deliveries] == ["chat"]


async def test_simple_create_with_defined_delivery() -> None:
    ctx = TestingContext(deliveries=DELIVERY, transport_types=[GenericTransport])
    await ctx.test_initialize()

    assert list(ctx.delivery_registry.deliveries.keys()) == ["chat"]
    assert [d.name for d in ctx.delivery_registry.implicit_deliveries] == ["chat"]


async def test_simple_create_with_only_default_deliveries() -> None:
    ctx = TestingContext(deliveries={}, transport_types=[GenericTransport])
    await ctx.test_initialize()

    assert list(ctx.delivery_registry.deliveries.keys()) == []
    assert [d.name for d in ctx.delivery_registry.implicit_deliveries] == []


async def test_simple_create_with_only_autogenerated_deliveries() -> None:
    ctx = TestingContext(deliveries={}, transport_types=[GenericTransport, NotifyEntityTransport])
    await ctx.test_initialize()

    assert list(ctx.delivery_registry.deliveries.keys()) == ["DEFAULT_notify_entity"]
    assert [d.name for d in ctx.delivery_registry.implicit_deliveries] == ["DEFAULT_notify_entity"]


async def test_resolve_name_falls_back_to_default_prefixed_delivery() -> None:
    ctx = TestingContext(deliveries={}, transport_types=[GenericTransport, NotifyEntityTransport])
    await ctx.test_initialize()

    # bare transport name resolves to the auto-configured DEFAULT_-prefixed delivery
    assert ctx.delivery_registry.resolve_name("notify_entity") == "DEFAULT_notify_entity"
    # already-existing name is left untouched
    assert ctx.delivery_registry.resolve_name("DEFAULT_notify_entity") == "DEFAULT_notify_entity"
    # no delivery under either spelling - name is returned unchanged (still not found)
    assert ctx.delivery_registry.resolve_name("no_such_delivery") == "no_such_delivery"


async def test_resolve_name_prefers_a_delivery_named_exactly_that() -> None:
    ctx = TestingContext(deliveries=DELIVERY)
    ctx.add_delivery("notify_entity", TRANSPORT_NOTIFY_ENTITY)
    await ctx.test_initialize()

    # a delivery literally named "notify_entity" exists, so it's preferred over any
    # same-transport DEFAULT_notify_entity that might otherwise have been generated
    assert "DEFAULT_notify_entity" not in ctx.delivery_registry.deliveries
    assert ctx.delivery_registry.resolve_name("notify_entity") == "notify_entity"


async def test_autogenerated_delivery_if_no_configured_delivery() -> None:
    ctx = TestingContext(
        deliveries=DELIVERY,
    )
    await ctx.test_initialize()
    assert "DEFAULT_notify_entity" in ctx.delivery_registry.deliveries


async def test_no_autogenerated_delivery_if_configured_delivery() -> None:
    ctx = TestingContext(
        deliveries=DELIVERY,
    )
    ctx.add_delivery("my_notify_entities", TRANSPORT_NOTIFY_ENTITY)
    await ctx.test_initialize()

    assert "DEFAULT_notify_entity" not in ctx.delivery_registry.deliveries
    assert "my_notify_entities" in ctx.delivery_registry.deliveries


async def test_autogenerated_delivery_respects_transport_status() -> None:
    ctx = TestingContext(
        deliveries=DELIVERY,
        transports={TRANSPORT_NOTIFY_ENTITY: {CONF_ENABLED: False}},
    )
    await ctx.test_initialize()
    assert "DEFAULT_notify_entity" not in ctx.delivery_registry.deliveries


async def test_expose_entities_hides_transport_without_prerequisites_or_delivery(hass: HomeAssistant) -> None:
    ctx = TestingContext(homeassistant=hass, deliveries={}, transport_types=[TelegramTransport, PersistentTransport])
    await ctx.test_initialize()
    ctx.delivery_registry.expose_entities(ctx.hass_api)

    # telegram has no config entry and no explicit delivery, so no switch
    assert hass.states.get("binary_sensor.supernotify_transport_telegram") is None
    # persistent has no prerequisites to check, so it's always available
    assert hass.states.get("binary_sensor.supernotify_transport_persistent") is not None


async def test_expose_entities_shows_available_transport_even_when_disabled(hass: HomeAssistant) -> None:
    """A transport with real prerequisites still gets a switch while toggled off in
    config, so it can be switched back on - only a genuinely unusable transport is hidden."""
    hass.states.async_set("notify.mock_notify_target", "unknown")
    ctx = TestingContext(
        homeassistant=hass,
        deliveries={},
        transport_types=[NotifyEntityTransport],
        transports={TRANSPORT_NOTIFY_ENTITY: {CONF_ENABLED: False}},
    )
    await ctx.test_initialize()
    ctx.delivery_registry.expose_entities(ctx.hass_api)

    entity_state = hass.states.get("binary_sensor.supernotify_transport_notify_entity")
    assert entity_state is not None
    assert entity_state.state == "off"


async def test_transport_defaults_used_for_missing_service(hass: HomeAssistant, uninitialized_unmocked_config: Context) -> None:
    delivery = {"chatty": {CONF_TRANSPORT: TRANSPORT_GENERIC, CONF_TARGET: ["chan1", "chan2"]}}
    context = uninitialized_unmocked_config
    context.delivery_registry._config_deliveries = delivery
    uut = GenericTransport(context, {CONF_DELIVERY_DEFAULTS: {CONF_ACTION: "notify.slackity"}})
    context.configure_for_tests(transport_instances=[uut])
    await context.initialize()
    await context.delivery_registry.initialize(context)

    await uut.initialize()
    assert list(uut.delivery_registry.deliveries.keys()) == ["chatty"]
    assert uut.delivery_registry.deliveries["chatty"].action == "notify.slackity"
