from __future__ import annotations

import copy
from typing import TYPE_CHECKING, Any

from homeassistant.const import CONF_ACTION, CONF_ENABLED, CONF_TARGET

from custom_components.supernotify.const import (
    CONF_DELIVERY_DEFAULTS,
    CONF_INCLUSION,
    CONF_LOAD,
    CONF_TRANSPORT,
    INCLUSION_BY_SCENARIO,
    INCLUSION_DEFAULT,
    INCLUSION_FALLBACK,
    INCLUSION_FALLBACK_ON_ERROR,
    TRANSPORT_ALEXA,
    TRANSPORT_ALEXA_MEDIA_PLAYER,
    TRANSPORT_CHIME,
    TRANSPORT_EMAIL,
    TRANSPORT_GENERIC,
    TRANSPORT_NOTIFY_ENTITY,
    TRANSPORT_PERSISTENT,
    TRANSPORT_SMS,
)
from custom_components.supernotify.transports.generic import GenericTransport
from custom_components.supernotify.transports.notify_entity import NotifyEntityTransport

from .hass_setup_lib import TestingContext

if TYPE_CHECKING:
    from homeassistant.core import HomeAssistant

    from custom_components.supernotify.context import Context

DELIVERY: dict[str, Any] = {
    "email": {CONF_TRANSPORT: TRANSPORT_EMAIL, CONF_ACTION: "notify.smtp"},
    "text": {CONF_TRANSPORT: TRANSPORT_SMS, CONF_ACTION: "notify.sms"},
    "chime": {CONF_TRANSPORT: TRANSPORT_CHIME, "target": ["switch.bell_1", "script.siren_2"]},
    "alexa_devices": {CONF_TRANSPORT: TRANSPORT_ALEXA, CONF_ACTION: "notify.send_message"},
    "alexa_media_player": {CONF_TRANSPORT: TRANSPORT_ALEXA_MEDIA_PLAYER, CONF_ACTION: "notify.alexa_media_player"},
    "chat": {CONF_TRANSPORT: TRANSPORT_GENERIC, CONF_ACTION: "notify.my_chat_server"},
    "persistent": {CONF_TRANSPORT: TRANSPORT_PERSISTENT, CONF_INCLUSION: [INCLUSION_BY_SCENARIO]},
}


async def test_simple_create_with_defined_default_delivery() -> None:
    delivery_config = copy.deepcopy(DELIVERY)
    delivery_config["chat"]["selection"] = "default"
    ctx = TestingContext(deliveries=delivery_config, transport_types=[GenericTransport])
    await ctx.test_initialize()

    assert list(ctx.delivery_registry.deliveries.keys()) == ["chat"]
    assert [d.name for d in ctx.delivery_registry.implicit_deliveries] == ["chat"]


async def test_runtime_enabled_delivery_joins_implicit_and_fallback_lists() -> None:
    """A delivery disabled in config, then enabled at runtime (e.g. by its switch), is used
    implicitly and as a fallback just like one enabled in config."""
    ctx = TestingContext(
        deliveries={
            "chat": {
                CONF_TRANSPORT: TRANSPORT_GENERIC,
                CONF_ACTION: "notify.my_chat_server",
                CONF_ENABLED: False,
                CONF_INCLUSION: [INCLUSION_DEFAULT, INCLUSION_FALLBACK, INCLUSION_FALLBACK_ON_ERROR],
            }
        },
        transport_types=[GenericTransport],
    )
    await ctx.test_initialize()
    registry = ctx.delivery_registry
    assert registry.implicit_deliveries == []
    assert registry.fallback_by_default_deliveries == []
    assert registry.fallback_on_error_deliveries == []

    registry.deliveries["chat"].enabled = True

    assert [d.name for d in registry.implicit_deliveries] == ["chat"]
    assert [d.name for d in registry.fallback_by_default_deliveries] == ["chat"]
    assert [d.name for d in registry.fallback_on_error_deliveries] == ["chat"]


async def test_simple_create_with_defined_delivery() -> None:
    ctx = TestingContext(deliveries=DELIVERY, transport_types=[GenericTransport])
    await ctx.test_initialize()

    assert list(ctx.delivery_registry.deliveries.keys()) == ["chat"]
    # "chat" doesn't set its own inclusion, and the generic transport defaults to
    # explicit, so it inherits that and isn't implicitly selected
    assert [d.name for d in ctx.delivery_registry.implicit_deliveries] == []


async def test_simple_create_with_only_default_deliveries() -> None:
    ctx = TestingContext(deliveries={}, transport_types=[GenericTransport])
    await ctx.test_initialize()

    assert list(ctx.delivery_registry.deliveries.keys()) == []
    assert [d.name for d in ctx.delivery_registry.implicit_deliveries] == []


async def test_simple_create_with_only_autogenerated_deliveries() -> None:
    ctx = TestingContext(deliveries={}, transport_types=[GenericTransport, NotifyEntityTransport])
    await ctx.test_initialize()

    assert list(ctx.delivery_registry.deliveries.keys()) == ["notify_entity"]
    assert [d.name for d in ctx.delivery_registry.implicit_deliveries] == ["notify_entity"]


async def test_resolve_name_falls_back_to_plain_delivery() -> None:
    ctx = TestingContext(deliveries={}, transport_types=[GenericTransport, NotifyEntityTransport])
    await ctx.test_initialize()

    # legacy 'DEFAULT_x' name (from before deliveries were named plainly after their
    # transport) resolves to the current delivery that replaced it
    assert ctx.delivery_registry.resolve_name("DEFAULT_notify_entity") == "notify_entity"
    # already-existing name is left untouched
    assert ctx.delivery_registry.resolve_name("notify_entity") == "notify_entity"
    # no delivery under either spelling - name is returned unchanged (still not found)
    assert ctx.delivery_registry.resolve_name("no_such_delivery") == "no_such_delivery"


async def test_resolve_name_leaves_existing_name_unchanged() -> None:
    ctx = TestingContext(deliveries=DELIVERY)
    ctx.add_delivery("notify_entity", TRANSPORT_NOTIFY_ENTITY)
    await ctx.test_initialize()

    # the explicit "notify_entity" delivery overrides the auto-configured defaults,
    # so there's only ever the one delivery to resolve to
    assert "notify_entity" in ctx.delivery_registry.deliveries
    assert ctx.delivery_registry.resolve_name("notify_entity") == "notify_entity"


async def test_autogenerated_delivery_if_no_configured_delivery() -> None:
    ctx = TestingContext(
        deliveries=DELIVERY,
    )
    await ctx.test_initialize()
    assert "notify_entity" in ctx.delivery_registry.deliveries


async def test_autogenerated_delivery_alongside_configured_delivery() -> None:
    ctx = TestingContext(
        deliveries=DELIVERY,
    )
    ctx.add_delivery("my_notify_entities", TRANSPORT_NOTIFY_ENTITY)
    await ctx.test_initialize()

    # the auto-configured delivery is created regardless of the explicit one, since
    # they have unique targets only one will be called
    assert "notify_entity" in ctx.delivery_registry.deliveries
    assert "my_notify_entities" in ctx.delivery_registry.deliveries


async def test_autogenerated_delivery_respects_transport_status() -> None:
    ctx = TestingContext(
        deliveries=DELIVERY,
        transports={TRANSPORT_NOTIFY_ENTITY: {CONF_ENABLED: False}},
    )
    await ctx.test_initialize()
    assert "notify_entity" in ctx.delivery_registry.deliveries
    assert ctx.delivery_registry.deliveries["notify_entity"].enabled is False


async def test_unloaded_transport_has_no_autogenerated_delivery() -> None:
    ctx = TestingContext(
        deliveries=DELIVERY,
        transports={TRANSPORT_NOTIFY_ENTITY: {CONF_LOAD: False}},
    )
    await ctx.test_initialize()
    assert "notify_entity" not in ctx.delivery_registry.deliveries
    assert TRANSPORT_NOTIFY_ENTITY not in ctx.delivery_registry.transports


async def test_transport_defaults_used_for_missing_service(hass: HomeAssistant, uninitialized_unmocked_config: Context) -> None:
    delivery = {"chatty": {CONF_TRANSPORT: TRANSPORT_GENERIC, CONF_TARGET: ["chan1", "chan2"]}}
    context = uninitialized_unmocked_config
    context.delivery_registry._config_deliveries = delivery
    uut = GenericTransport(context, {CONF_DELIVERY_DEFAULTS: {CONF_ACTION: "notify.slackity"}})
    context.configure_for_tests(transport_instances=[uut])
    await context.initialize()
    await context.delivery_registry.initialize(context)

    await uut.initialize()
    # "chatty" is explicit; "generic" is auto-configured alongside it from the same
    # transport's delivery_defaults, named plainly and explicit-only since "chatty" already
    # covers implicit selection for this transport
    assert set(uut.delivery_registry.deliveries.keys()) == {"chatty", "generic"}
    assert uut.delivery_registry.deliveries["chatty"].action == "notify.slackity"
