# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Supernotify

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.13"]

    steps:
    - name: Checkout main
      uses: actions/checkout@v5

    - name: Deploy docs
      run: |
        if [ -f requirements_docs.txt ]; then pip install -r requirements_docs.txt; fi
        mkdocs gh-deploy --force --config-file mkdocs.yml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REQUIREMENTS: requirements_docs.txt

